name: Build K2P-4.4

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        git clone https://github.com/hanwckf/padavan-4.4.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: "K2P"
      run: |
        cd /opt/rt-n56u/trunk
        # 插件配置 - 按需修改
        #####################################################################################
        sed -i 's/FRP_VER := 0.29.0/FRP_VER := 0.39.0/g' user/frp/Makefile  # 修改frp版本到0.39.0
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_FRPC=n/CONFIG_FIRMWARE_INCLUDE_FRPC=y/g' configs/templates/${TNAME}.config # 开启FRPC模块
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_LRZSZ=n/CONFIG_FIRMWARE_INCLUDE_LRZSZ=y/g' configs/templates/${TNAME}.config # 开启LRZSZ模块
        # 增加smartdns拓展
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> configs/templates/${TNAME}.config # smartdns
        ####################################################################################
        fakeroot ./build_firmware_modify ${TNAME}
        sudo mv -f images/*.trx /opt/images/
    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: K2P-4.4
        path: /opt/images/*.trx
